[general]
live_config_reload = true
import = ["~/.config/alacritty/catppuccin-macchiato.toml"]

[window]
opacity = 0.8
decorations = "None"
decorations_theme_variant = "Dark"
dynamic_padding = true
startup_mode = "Windowed"

[font]
normal.family = "FiraCode Nerd Font"
bold.family = "FiraCode Nerd Font"
size = 12.0

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ''',│`|:"' ()[]{}<>'''

